FROM cgr.dev/chainguard/go:latest AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /bin/outbound ./cmd/outbound

FROM cgr.dev/chainguard/static:latest
COPY --from=builder /bin/outbound /outbound
ENTRYPOINT ["/outbound"]
