FROM cgr.dev/chainguard/go AS builder

WORKDIR /build
ENV CGO_ENABLED=0
ENV GOTOOLCHAIN=auto
COPY ./go.mod .
COPY ./go.sum .
COPY ./cmd/ ./cmd/
COPY ./internal/ ./internal/
RUN go build -o bin/outbound ./cmd/outbound

FROM cgr.dev/chainguard/static
WORKDIR /app
COPY --from=builder /build/bin/outbound .
ENTRYPOINT ["/app/outbound"]
