apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: bolt-proxy-inbound
  namespace: appsec
  labels:
    team: appsec
spec:
  image: "{{image}}"
  port: 8080
  replicas:
    min: 2
    max: 2
  strategy:
    type: RollingUpdate
  ingresses:
    - https://appsec-bolt-proxy.intern.nav.no
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: bolt-proxy-outbound
          namespace: appsec
          cluster: dev-gcp
        - application: bolt-proxy-outbound
          namespace: appsec
          cluster: dev-fss
        - application: bolt-proxy-outbound
          namespace: appsec
          cluster: prod-fss
  env:
    - name: NEO4J_BOLT_ADDR
      value: "neo4j-bolt.appsec.svc.cluster.local:7687"
  liveness:
    path: /isalive
    initialDelay: 5
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /isready
    initialDelay: 5
    periodSeconds: 10
    failureThreshold: 3
  prometheus:
    enabled: true
    path: /metrics
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi
