name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
      - name: Run tests
        run: go test ./...

  build-outbound:
    name: Build outbound image
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Build and push outbound image
        id: build
        uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5 # v0
        with:
          team: appsec
          image_suffix: outbound
          build_args: BINARY=outbound

  build-inbound:
    name: Build inbound image
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Build and push inbound image
        id: build
        uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5 # v0
        with:
          team: appsec
          image_suffix: inbound
          build_args: BINARY=inbound

  deploy-inbound:
    name: Deploy inbound (prod-gcp)
    needs: build-inbound
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Deploy inbound to prod-gcp
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/inbound-prod-gcp.yaml
          IMAGE: ${{ needs.build-inbound.outputs.image }}

  deploy-outbound:
    name: Deploy outbound
    needs: build-outbound
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        include:
          - cluster: dev-gcp
          - cluster: dev-fss
          - cluster: prod-fss
      fail-fast: false
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Deploy outbound to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/outbound-${{ matrix.cluster }}.yaml
          IMAGE: ${{ needs.build-outbound.outputs.image }}
